### ISSUE TITLE
how to use OpenMP in Ceres Solver?

### ISSUE THREAD

**Issue by Ayangdanny** [tbennun/ceres-windows#17]
I use AnalyticCostfunction. In the "virtual bool Evaluate()" function I have some code used to calculate  residuals and jacobians. In these code I try to use "#pragma omp parallel for" to improve the performance, but it dons't make any sense. If I run the same code in other place (mine rather than ceres‘s functions),the OpenMP make sense very well. I concer about whether there are some tricks when use OpenMP in Ceres functions.

**Comment by tbennun** [comment]
Hi @Ayangdanny,
Since this issue directly relates to ceres-solver rather than the Windows build port, I would suggest that you open an issue in https://github.com/ceres-solver/ceres-solver instead.

As for your question, you may want to enable Nested Parallelism in OpenMP and see if you run with multiple threads.

Thanks!

**Comment by Ayangdanny** [comment]
OK,Thanks!
